module.exports = (sequelize, DataTypes) => {
  return sequelize.define('SupportTicket', {
    ticket_id: { type: DataTypes.STRING, primaryKey: true },
    awb_or_lr_no: DataTypes.STRING,
    category: DataTypes.STRING,
    sub_category: DataTypes.STRING,
    description: DataTypes.TEXT,
    status: DataTypes.STRING,
    additional_fields: DataTypes.TEXT,          // TEXT is safe across MySQL versions
    created_at: DataTypes.DATE,
    updated_at: DataTypes.DATE,
    lr_no: DataTypes.STRING,
    order_id: DataTypes.INTEGER,
    client_id: DataTypes.INTEGER,               // use STRING if column is varchar
    tagged_api: DataTypes.STRING,
    aggregator_id: DataTypes.INTEGER,
    forwarder_id: DataTypes.INTEGER,
    shipment_status: DataTypes.STRING,
    eta: DataTypes.INTEGER,
    pickup_zone: DataTypes.STRING,
    destination_zone: DataTypes.STRING,
    shipment_created_at: DataTypes.DATE,
    insurance_type: DataTypes.STRING,
    volumetric_weight: DataTypes.DECIMAL(10,2),
    chargeable_weight: DataTypes.DECIMAL(10,2),
    base_rate: DataTypes.DECIMAL(10,2),
    total_additional: DataTypes.DECIMAL(10,2),
    total_gst: DataTypes.DECIMAL(10,2),
    total_lr_charges: DataTypes.DECIMAL(10,2),
    billing_status: DataTypes.STRING,
    shipment_details_raw: DataTypes.TEXT,
    weight_details_raw: DataTypes.TEXT,
    notify_enabled: DataTypes.BOOLEAN,
    notify_email_from: DataTypes.STRING,
    notify_to: DataTypes.TEXT,
    notify_cc: DataTypes.TEXT,
    notify_sent: DataTypes.BOOLEAN,
    notify_error: DataTypes.TEXT,
    notification_raw: DataTypes.TEXT,
  }, {
    tableName: 'tbl_support_tickets',
    timestamps: false,
    underscored: true,
  });
};
